In [7]:
import requests
import json
import pandas as pd

In [8]:
# Initialize an empty DataFrame to store the data
movie_df = pd.DataFrame()

# Iterate through the range of movie IDs
for movie_id in range(1, 800):
    # Make a request for the current movie ID
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=539ba2f0d8506e0d227fed57bdf4e8b7"
    response = requests.get(url)
    movie_data = response.json()

    # Check if the movie data contains the required keys
    if all(key in movie_data for key in ('title', 'release_date', 'budget', 'revenue', 'runtime', 'vote_average', 'vote_count', 'overview', 'tagline', 'genres', 'production_companies', 'production_countries')):
        # Convert the data to a DataFrame and append it to the overall DataFrame
        movie_row = pd.DataFrame({
            'title': [movie_data['title']],
            'release_date': [movie_data['release_date']],
            'budget': [movie_data['budget']],
            'revenue': [movie_data['revenue']],
            'runtime': [movie_data['runtime']],
            'vote_average': [movie_data['vote_average']],
            'vote_count': [movie_data['vote_count']],
            'overview': [movie_data['overview']],
            'tagline': [movie_data['tagline']],
            'genres': [[genre['name'] for genre in movie_data['genres']]],
            'production_companies': [[company['name'] for company in movie_data['production_companies']]],
            'production_countries': [[country['name'] for country in movie_data['production_countries']]]
        })
        movie_df = movie_df.append(movie_row, ignore_index=True)
    else:
        print(f"Movie data for ID {movie_id} is missing a required key.")

# Display the resulting DataFrame
print(movie_df)

Movie data for ID 1 is missing a required key.
Movie data for ID 4 is missing a required key.

/var/folders/f1/kkdf80nn44q445kjsvdzsnm80000gn/T/ipykernel_1045/804359426.py:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  movie_df = movie_df.append(movie_row, ignore_index=True)

Movie data for ID 7 is missing a required key.
Movie data for ID 10 is missing a required key.
Movie data for ID 23 is missing a required key.
Movie data for ID 29 is missing a required key.
Movie data for ID 30 is missing a required key.
Movie data for ID 31 is missing a required key.
Movie data for ID 32 is missing a required key.
Movie data for ID 34 is missing a required key.
Movie data for ID 36 is missing a required key.
Movie data for ID 37 is missing a required key.
Movie data for ID 39 is missing a required key.
Movie data for ID 40 is missing a required key.
Movie data for ID 41 is missing a required key.
Movie data for ID 42 is missing a required key.
Movie data for ID 43 is missing a required key.
Movie data for ID 44 is missing a required key.
Movie data for ID 45 is missing a required key.
Movie data for ID 46 is missing a required key.
Movie data for ID 47 is missing a required key.
Movie data for ID 48 is missing a required key.
Movie data for ID 49 is missing a required key.
Movie data for ID 50 is missing a required key.
Movie data for ID 51 is missing a required key.
Movie data for ID 52 is missing a required key.
Movie data for ID 53 is missing a required key.
Movie data for ID 54 is missing a required key.
Movie data for ID 56 is missing a required key.
Movie data for ID 57 is missing a required key.
Movie data for ID 60 is missing a required key.
Movie data for ID 61 is missing a required key.
Movie data for ID 72 is missing a required key.
Movie data for ID 84 is missing a required key.
Movie data for ID 119 is missing a required key.
Movie data for ID 130 is missing a required key.
Movie data for ID 131 is missing a required key.
Movie data for ID 151 is missing a required key.
Movie data for ID 181 is missing a required key.
Movie data for ID 188 is missing a required key.
Movie data for ID 202 is missing a required key.
Movie data for ID 208 is missing a required key.
Movie data for ID 209 is missing a required key.
Movie data for ID 210 is missing a required key.
Movie data for ID 230 is missing a required key.
Movie data for ID 263 is missing a required key.
Movie data for ID 264 is missing a required key.
Movie data for ID 282 is missing a required key.
Movie data for ID 283 is missing a required key.
Movie data for ID 295 is missing a required key.
Movie data for ID 304 is missing a required key.
Movie data for ID 305 is missing a required key.
Movie data for ID 323 is missing a required key.
Movie data for ID 324 is missing a required key.
Movie data for ID 325 is missing a required key.
Movie data for ID 328 is missing a required key.
Movie data for ID 352 is missing a required key.
Movie data for ID 353 is missing a required key.
Movie data for ID 354 is missing a required key.
Movie data for ID 355 is missing a required key.
Movie data for ID 356 is missing a required key.
Movie data for ID 357 is missing a required key.
Movie data for ID 358 is missing a required key.
Movie data for ID 359 is missing a required key.
Movie data for ID 360 is missing a required key.
Movie data for ID 361 is missing a required key.
Movie data for ID 362 is missing a required key.
Movie data for ID 365 is missing a required key.
Movie data for ID 366 is missing a required key.
Movie data for ID 367 is missing a required key.
Movie data for ID 368 is missing a required key.
Movie data for ID 369 is missing a required key.
Movie data for ID 370 is missing a required key.
Movie data for ID 371 is missing a required key.
Movie data for ID 372 is missing a required key.
Movie data for ID 373 is missing a required key.
Movie data for ID 374 is missing a required key.
Movie data for ID 375 is missing a required key.
Movie data for ID 376 is missing a required key.
Movie data for ID 382 is missing a required key.
Movie data for ID 384 is missing a required key.
Movie data for ID 385 is missing a required key.
Movie data for ID 386 is missing a required key.
Movie data for ID 394 is missing a required key.
Movie data for ID 399 is missing a required key.
Movie data for ID 412 is missing a required key.
Movie data for ID 413 is missing a required key.
Movie data for ID 416 is missing a required key.
Movie data for ID 417 is missing a required key.
Movie data for ID 418 is missing a required key.
Movie data for ID 420 is missing a required key.
Movie data for ID 432 is missing a required key.
Movie data for ID 443 is missing a required key.
Movie data for ID 444 is missing a required key.
Movie data for ID 447 is missing a required key.
Movie data for ID 448 is missing a required key.
Movie data for ID 449 is missing a required key.
Movie data for ID 450 is missing a required key.
Movie data for ID 456 is missing a required key.
Movie data for ID 461 is missing a required key.
Movie data for ID 463 is missing a required key.
Movie data for ID 472 is missing a required key.
Movie data for ID 474 is missing a required key.
Movie data for ID 477 is missing a required key.
Movie data for ID 478 is missing a required key.
Movie data for ID 484 is missing a required key.
Movie data for ID 485 is missing a required key.
Movie data for ID 486 is missing a required key.
Movie data for ID 487 is missing a required key.
Movie data for ID 495 is missing a required key.
Movie data for ID 498 is missing a required key.
Movie data for ID 514 is missing a required key.
Movie data for ID 515 is missing a required key.
Movie data for ID 516 is missing a required key.
Movie data for ID 517 is missing a required key.
Movie data for ID 518 is missing a required key.
Movie data for ID 519 is missing a required key.
Movie data for ID 520 is missing a required key.
Movie data for ID 528 is missing a required key.
Movie data for ID 529 is missing a required key.
Movie data for ID 545 is missing a required key.
Movie data for ID 556 is missing a required key.
Movie data for ID 566 is missing a required key.
Movie data for ID 569 is missing a required key.
Movie data for ID 589 is missing a required key.
Movie data for ID 610 is missing a required key.
Movie data for ID 611 is missing a required key.
Movie data for ID 645 is missing a required key.
Movie data for ID 656 is missing a required key.
Movie data for ID 683 is missing a required key.
Movie data for ID 684 is missing a required key.
Movie data for ID 715 is missing a required key.
Movie data for ID 716 is missing a required key.
Movie data for ID 717 is missing a required key.
Movie data for ID 718 is missing a required key.
Movie data for ID 719 is missing a required key.
Movie data for ID 720 is missing a required key.
Movie data for ID 721 is missing a required key.
Movie data for ID 722 is missing a required key.
Movie data for ID 723 is missing a required key.
Movie data for ID 724 is missing a required key.
Movie data for ID 725 is missing a required key.
Movie data for ID 726 is missing a required key.
Movie data for ID 727 is missing a required key.
Movie data for ID 728 is missing a required key.
Movie data for ID 729 is missing a required key.
Movie data for ID 730 is missing a required key.
Movie data for ID 731 is missing a required key.
Movie data for ID 732 is missing a required key.
Movie data for ID 733 is missing a required key.
Movie data for ID 734 is missing a required key.
Movie data for ID 735 is missing a required key.
Movie data for ID 736 is missing a required key.
Movie data for ID 737 is missing a required key.
Movie data for ID 738 is missing a required key.
Movie data for ID 739 is missing a required key.
Movie data for ID 740 is missing a required key.
Movie data for ID 741 is missing a required key.
Movie data for ID 748 is missing a required key.
Movie data for ID 749 is missing a required key.
                                title release_date    budget    revenue  \
0                               Ariel   1988-10-21         0          0
1                 Shadows in Paradise   1986-10-17         0          0
2                          Four Rooms   1995-12-09   4000000    4257354
3                      Judgment Night   1993-10-15  21000000   12136938
4    Life in Loops (A Megacities RMX)   2006-01-01     42000          0
..                                ...          ...       ...        ...
634                    City of Angels   1998-04-10  55000000  198685114
635                  Cruel Intentions   1999-03-05  10500000   76347426
636                           Persona   1966-10-18         0          0
637                 Annaluise & Anton   1953-08-26         0          0
638                 Annaluise & Anton   1999-03-11         0          0

     runtime  vote_average  vote_count  \
0         73         7.055         247
1          0         7.200         268
2         98         5.758        2345
3        109         6.558         283
4         80         7.708          24
..       ...           ...         ...
634      114         6.759        1866
635       98         6.791        2818
636       83         8.300        1802
637       91         7.083           6
638      107         7.091          22

                                              overview  \
0    Taisto Kasurinen is a Finnish coal miner whose...
1    An episode in the life of Nikander, a garbage ...
2    It's Ted the Bellhop's first night on the job....
3    While racing to a boxing match, Frank, Mike, J...
4    Timo Novotny labels his new project an experim...
..                                                 ...
634  When guardian angel Seth - who invisibly watch...
635  Slaking a thirst for dangerous games, Kathryn ...
636  A young nurse, Alma, is put in charge of Elisa...
637  Despite their social differences Luise, called...
638  Luise, called Pünktchen, and Anton are closest...

                                               tagline  \
0
1
2    Twelve outrageous guests. Four scandalous requ...
3       Don't move. Don't whisper. Don't even breathe.
4                                  A Megacities remix.
..                                                 ...
634  She didn't believe in angels until she fell in...
635  In the game of seduction, there is only one ru...
636
637
638

                        genres  \
0       [Drama, Comedy, Crime]
1     [Drama, Comedy, Romance]
2              [Crime, Comedy]
3    [Action, Crime, Thriller]
4                [Documentary]
..                         ...
634  [Romance, Drama, Fantasy]
635           [Drama, Romance]
636                    [Drama]
637    [Family, Drama, Comedy]
638    [Family, Comedy, Drama]

                                  production_companies  \
0                          [Villealfa Filmproductions]
1                          [Villealfa Filmproductions]
2                              [Miramax, A Band Apart]
3                           [Largo Entertainment, JVC]
4                                            [inLoops]
..                                                 ...
634  [Atlas Entertainment, Monarchy Enterprises B.V...
635  [Columbia Pictures, Cruel Productions, Newmark...
636                                       [SF Studios]
637                                 [Rhombus Ringfilm]
638                                     [Lunaris Film]

                    production_countries
0                              [Finland]
1                              [Finland]
2             [United States of America]
3             [United States of America]
4                              [Austria]
..                                   ...
634  [Germany, United States of America]
635           [United States of America]
636                             [Sweden]
637                   [Austria, Germany]
638                            [Germany]

[639 rows x 12 columns]

In [9]:
movie_df

,title,release_date,budget,revenue,runtime,vote_average,vote_count,overview,tagline,genres,production_companies,production_countries
0,Ariel,1988-10-21,0,0,73,7.055,247,Taisto Kasurinen is a Finnish coal miner whose...,,"[Drama, Comedy, Crime]",[Villealfa Filmproductions],[Finland]
1,Shadows in Paradise,1986-10-17,0,0,0,7.200,268,"An episode in the life of Nikander, a garbage ...",,"[Drama, Comedy, Romance]",[Villealfa Filmproductions],[Finland]
2,Four Rooms,1995-12-09,4000000,4257354,98,5.758,2345,It's Ted the Bellhop's first night on the job....,Twelve outrageous guests. Four scandalous requ...,"[Crime, Comedy]","[Miramax, A Band Apart]",[United States of America]
3,Judgment Night,1993-10-15,21000000,12136938,109,6.558,283,"While racing to a boxing match, Frank, Mike, J...",Don't move. Don't whisper. Don't even breathe.,"[Action, Crime, Thriller]","[Largo Entertainment, JVC]",[United States of America]
4,Life in Loops (A Megacities RMX),2006-01-01,42000,0,80,7.708,24,Timo Novotny labels his new project an experim...,A Megacities remix.,[Documentary],[inLoops],[Austria]
...,...,...,...,...,...,...,...,...,...,...,...,...
634,City of Angels,1998-04-10,55000000,198685114,114,6.759,1866,When guardian angel Seth - who invisibly watch...,She didn't believe in angels until she fell in...,"[Romance, Drama, Fantasy]","[Atlas Entertainment, Monarchy Enterprises B.V...","[Germany, United States of America]"
635,Cruel Intentions,1999-03-05,10500000,76347426,98,6.791,2818,"Slaking a thirst for dangerous games, Kathryn ...","In the game of seduction, there is only one ru...","[Drama, Romance]","[Columbia Pictures, Cruel Productions, Newmark...",[United States of America]
636,Persona,1966-10-18,0,0,83,8.300,1802,"A young nurse, Alma, is put in charge of Elisa...",,[Drama],[SF Studios],[Sweden]
637,Annaluise & Anton,1953-08-26,0,0,91,7.083,6,"Despite their social differences Luise, called...",,"[Family, Drama, Comedy]",[Rhombus Ringfilm],"[Austria, Germany]"
638,Annaluise & Anton,1999-03-11,0,0,107,7.091,22,"Luise, called Pünktchen, and Anton are closest...",,"[Family, Comedy, Drama]",[Lunaris Film],[Germany]

In [10]:
df = movie_df.applymap(lambda x: ', '.join(x) if isinstance(x, list) else x)
df

,title,release_date,budget,revenue,runtime,vote_average,vote_count,overview,tagline,genres,production_companies,production_countries
0,Ariel,1988-10-21,0,0,73,7.055,247,Taisto Kasurinen is a Finnish coal miner whose...,,"Drama, Comedy, Crime",Villealfa Filmproductions,Finland
1,Shadows in Paradise,1986-10-17,0,0,0,7.200,268,"An episode in the life of Nikander, a garbage ...",,"Drama, Comedy, Romance",Villealfa Filmproductions,Finland
2,Four Rooms,1995-12-09,4000000,4257354,98,5.758,2345,It's Ted the Bellhop's first night on the job....,Twelve outrageous guests. Four scandalous requ...,"Crime, Comedy","Miramax, A Band Apart",United States of America
3,Judgment Night,1993-10-15,21000000,12136938,109,6.558,283,"While racing to a boxing match, Frank, Mike, J...",Don't move. Don't whisper. Don't even breathe.,"Action, Crime, Thriller","Largo Entertainment, JVC",United States of America
4,Life in Loops (A Megacities RMX),2006-01-01,42000,0,80,7.708,24,Timo Novotny labels his new project an experim...,A Megacities remix.,Documentary,inLoops,Austria
...,...,...,...,...,...,...,...,...,...,...,...,...
634,City of Angels,1998-04-10,55000000,198685114,114,6.759,1866,When guardian angel Seth - who invisibly watch...,She didn't believe in angels until she fell in...,"Romance, Drama, Fantasy","Atlas Entertainment, Monarchy Enterprises B.V....","Germany, United States of America"
635,Cruel Intentions,1999-03-05,10500000,76347426,98,6.791,2818,"Slaking a thirst for dangerous games, Kathryn ...","In the game of seduction, there is only one ru...","Drama, Romance","Columbia Pictures, Cruel Productions, Newmarke...",United States of America
636,Persona,1966-10-18,0,0,83,8.300,1802,"A young nurse, Alma, is put in charge of Elisa...",,Drama,SF Studios,Sweden
637,Annaluise & Anton,1953-08-26,0,0,91,7.083,6,"Despite their social differences Luise, called...",,"Family, Drama, Comedy",Rhombus Ringfilm,"Austria, Germany"
638,Annaluise & Anton,1999-03-11,0,0,107,7.091,22,"Luise, called Pünktchen, and Anton are closest...",,"Family, Comedy, Drama",Lunaris Film,Germany

In [11]:
df = df.drop(['overview','tagline'], axis=1)

In [ ]:
df.isnull().sum()

In [12]:
df

,title,release_date,budget,revenue,runtime,vote_average,vote_count,genres,production_companies,production_countries
0,Ariel,1988-10-21,0,0,73,7.055,247,"Drama, Comedy, Crime",Villealfa Filmproductions,Finland
1,Shadows in Paradise,1986-10-17,0,0,0,7.200,268,"Drama, Comedy, Romance",Villealfa Filmproductions,Finland
2,Four Rooms,1995-12-09,4000000,4257354,98,5.758,2345,"Crime, Comedy","Miramax, A Band Apart",United States of America
3,Judgment Night,1993-10-15,21000000,12136938,109,6.558,283,"Action, Crime, Thriller","Largo Entertainment, JVC",United States of America
4,Life in Loops (A Megacities RMX),2006-01-01,42000,0,80,7.708,24,Documentary,inLoops,Austria
...,...,...,...,...,...,...,...,...,...,...
634,City of Angels,1998-04-10,55000000,198685114,114,6.759,1866,"Romance, Drama, Fantasy","Atlas Entertainment, Monarchy Enterprises B.V....","Germany, United States of America"
635,Cruel Intentions,1999-03-05,10500000,76347426,98,6.791,2818,"Drama, Romance","Columbia Pictures, Cruel Productions, Newmarke...",United States of America
636,Persona,1966-10-18,0,0,83,8.300,1802,Drama,SF Studios,Sweden
637,Annaluise & Anton,1953-08-26,0,0,91,7.083,6,"Family, Drama, Comedy",Rhombus Ringfilm,"Austria, Germany"
638,Annaluise & Anton,1999-03-11,0,0,107,7.091,22,"Family, Comedy, Drama",Lunaris Film,Germany

In [13]:
df.to_csv('/Users/dslearner23/Downloads/my_movies.csv', index=False)